### ISSUE TITLE
[BUG] Builder is not registered when using `-b` option to sphinx-build

### ISSUE THREAD

**Issue by zanchey** [liran-funaro/sphinx-markdown-builder#13]
In sphinx-markdown-builder 0.5.5, the builder can be activated manually using the `-b` option to `sphinx-build`, without adding it to the extensions list in the configuration.

In 0.6.0-0.6.5, this fails with
```
Sphinx error:
Builder name markdown not registered or available through entry point
``` 

To reproduce, using pipx for simplicity, but same occurs in a virtualenv:

```
pipx install sphinx
pipx inject sphinx sphinx-markdown-builder==0.5.5
sphinx-build -b markdown sourcedir outdir # works
pipx inject sphinx sphinx-markdown-builder==0.6.5 # or 0.6.0
sphinx-build -b markdown sourcedir outdir # error above is produced
```

Occurs on Debian Linux 11 and macOS 14, under both pipx and virtualenv.

I think the fix here is to update pyproject.toml - see https://www.sphinx-doc.org/en/master/development/builders.html

**Comment by liran-funaro** [comment]
Thank you for the report.
I'm sorry it took some time to reply. 
I attended to this issue in version 0.6.6.
Please check it out and update here if this works for you.

**Comment by zanchey** [comment]
Yes, that's great! Thanks.
